### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by MousaMohammed** [jananiarunachalam/Research-Paper-Summarization#1]
hi jananiarunachalam.
can you please share the link of the google drive that you store the data set in.  I tried to download it but I couldn't

**Comment by jananiarunachalam** [comment]
Here's the Google Drive to the Dataset: https://drive.google.com/drive/folders/1Xz78mg_5LLQUhumIqwQYw93apSsO3DFi?usp=sharing

**Comment by brahmakulkarni** [comment]
Does your pickle file have a dataframe with only these columns: "text", "filenames", "highlights", "body"?
