### ISSUE TITLE
Dataset pickle file format

### ISSUE THREAD

**Issue by brahmakulkarni** [jananiarunachalam/Research-Paper-Summarization#2]
Does your pickle file have a dataframe with only these columns: "text", "filenames", "highlights", "body"? Or are there any additional columns that you didn't mention in the comment before reading the pickle file in the abstract summarization related iPython notebook file?

**Comment by jananiarunachalam** [comment]
Yes, those are only columns as far as I can remember. Link to the "papers.pkl" file: https://drive.google.com/open?id=1RPsgg32xLBUwbMr3eV0uTqGuVgUQSGzu

**Comment by brahmakulkarni** [comment]
Thank you!
